baseURL = "https://lanre.wtf"
languageCode = "en-us"
title = "Lanre Adelowo's website"
theme = "lanreadelowo"
pygmentsUseClasses=true
disqusShortname = "adelowo"

[permalinks]
  blog = "blog/:year/:month/:day/:slug/"

[params]
  name = "Lanre Adelowo"
  email = "yo@lanre.wtf"
  homepage = "https://lanre.wtf"
  twitter = "https://twitter.com/lanreadelowo"
  github = "https://github.com/adelowo"
